package presentation;

import base.CommandeDao;
import domaine.Capsule;
import domaine.Commande;
import domaine.Employe;
import java.util.Calendar;
import metier.ListeCapsules;
import outils.Validation;

/**
 * 634.1 - Programmation - TP P02
 * 
 * Enregistrement d'une nouvelle commande pour un employé: Singleton
 * 
 * @author LKABOUSSE
 * @version 1.0
 */
public class FrmNouvelleCommande extends java.awt.Frame {
    
    private static FrmNouvelleCommande instance;
    private static FrmMain frmMain;
    private static Employe employe;
    //private static final String LBL_COMMANDEPOUR = "Commande pour ";
    private ListeCapsules listeCapsules;
    
    /* Constructeur */
    private FrmNouvelleCommande () {
        initComponents();
        chargerCapsules();
        chargerLabel();
        etatLabelsEtBoutons();
        lstCapsules.select(0);
    } //Constructeur
    
    public static FrmNouvelleCommande getInstance (FrmMain frm, Employe e) {
        if (instance == null) {frmMain = frm;  instance = new FrmNouvelleCommande();}
        employe = e; 
        return instance;
    } //getInstance
    
    /* Chargement des capsules dans la liste */
    private void chargerCapsules(){
        listeCapsules = new ListeCapsules();
        for (int i = 0; i < listeCapsules.size(); i++) {
            Capsule caps = (Capsule)listeCapsules.getCapsule(i);
            lstCapsules.add(caps.toString());
        }
    }//chargerCapsules
    
    /* Chargement du label de l'employé concerné : Erreur de type NullPointerException */
    private void chargerLabel(){
        //lblEmploye.setText(LBL_COMMANDEPOUR + employe.getNom());
    }//chargerLabel
    
    /* Gestion du label d'erreur et du bouton "Enregistrer" */
    private void etatLabelsEtBoutons(){
        boolean nbCapsules = Validation.isIntValid(tfNombre.getText());
         if (nbCapsules && Integer.parseInt(tfNombre.getText()) > 0) {
            lblErreur.setVisible(false);
            btnEnregistrer.setEnabled(true);
        }else{
            lblErreur.setVisible(true);
            btnEnregistrer.setEnabled(false);
        }
    }//etatLabelsEtBoutons
    
    /* Ajout de la commande */
    private void ajouterCommande(){
        Capsule caps = (Capsule)listeCapsules.getCapsule(lstCapsules.getSelectedIndex());
        int nombre = Integer.parseInt(tfNombre.getText());
        java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime());
        Commande comm = new Commande(employe, caps, nombre, date);
        CommandeDao.addCommande(comm);
        instance.dispose();
        frmMain.afficherCommandes();
    }//ajouterCommande

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method
     * is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmploye = new java.awt.Label();
        lstCapsules = new java.awt.List();
        lblNombre = new java.awt.Label();
        tfNombre = new java.awt.TextField();
        btnEnregistrer = new java.awt.Button();
        lblErreur = new java.awt.Label();

        setTitle("Compléter une commande");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblEmploye.setText("Commande pour ...");

        lblNombre.setText("Nombre de capsules");

        tfNombre.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                tfNombreTextValueChanged(evt);
            }
        });

        btnEnregistrer.setEnabled(false);
        btnEnregistrer.setLabel("Enregistrer la commande");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        lblErreur.setForeground(java.awt.Color.red);
        lblErreur.setText("La valeur saisie doit être un entier > 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lstCapsules, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErreur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstCapsules, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErreur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Fermeture de la fenêtre */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        instance.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void tfNombreTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_tfNombreTextValueChanged
        etatLabelsEtBoutons();
    }//GEN-LAST:event_tfNombreTextValueChanged

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        ajouterCommande();
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnEnregistrer;
    private java.awt.Label lblEmploye;
    private java.awt.Label lblErreur;
    private java.awt.Label lblNombre;
    private java.awt.List lstCapsules;
    private java.awt.TextField tfNombre;
    // End of variables declaration//GEN-END:variables

} // FrmNouvelleCommande
