package presentation;

import domaine.Commande;
import domaine.Employe;
import metier.ListeCapsules;
import outils.Validation;

/**
 * Module 634.1-Programmation - TP P02
 * 
 * Enregistrement d'une nouvelle commande pour un employé: Singleton
 * 
 * @author Peter DAEHNE - HEG Genève
 * @version 2.1
 */
public class FrmNouvelleCommande extends java.awt.Frame {
  
    private static final String COMMANDE_POUR = "Compléter la commande de ";

    private static FrmNouvelleCommande instance = new FrmNouvelleCommande(); /* L'unique instance */
    private static FrmMain frmMain; /* L'instance de la fenêtre principale */

    private ListeCapsules listeCapsules; /* Modèles pour la liste des capsules */
    private Employe employe; /* L'employé pour lequel on effectue la nouvelle commande */

    /* Constructeur */
    private FrmNouvelleCommande () {
        initComponents();
        chargerCapsules();
    } // Constructeur

    /** Retour de l'unique instance */
    public static FrmNouvelleCommande getInstance (FrmMain f) {
        frmMain = f;
        return instance;
    } // getInstance

    /** Définition de l'employé pour lequel on effectue la commande */
    public void setEmploye (Employe e) {
        employe = e;
        lblEmploye.setText(COMMANDE_POUR + e.toString());
        selectCapsule(0);
        tfNombre.setText("0"); lblErreur.setVisible(true);
    } // setEmploye

    /* Sélection de la capsule d'indice pos */
    private void selectCapsule (int pos) {listeCapsules.setPos(pos); lstCapsules.select(pos);}

    /* Chargement de la liste des capsules dans l'ordre des noms */
    private void chargerCapsules () {
        listeCapsules = new ListeCapsules();
        for (int k = 0; k < listeCapsules.size(); k++) {lstCapsules.add(listeCapsules.getCapsule(k).toString());}
        selectCapsule(0);
    } // chargerCapsules

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method
     * is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmploye = new java.awt.Label();
        lstCapsules = new java.awt.List();
        lblNombre = new java.awt.Label();
        tfNombre = new java.awt.TextField();
        btnEnregistrer = new java.awt.Button();
        lblErreur = new java.awt.Label();

        setTitle("Compléter une commande");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblEmploye.setText("Commande pour ...");

        lstCapsules.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstCapsulesItemStateChanged(evt);
            }
        });

        lblNombre.setText("Nombre de capsules");

        tfNombre.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                tfNombreTextValueChanged(evt);
            }
        });

        btnEnregistrer.setEnabled(false);
        btnEnregistrer.setLabel("Enregistrer la commande");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        lblErreur.setForeground(java.awt.Color.red);
        lblErreur.setText("La valeur saisie doit être un entier > 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lstCapsules, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErreur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstCapsules, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErreur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Fermeture de la fenêtre */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /* La valeur saisie a changé */
    private void tfNombreTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_tfNombreTextValueChanged
        String strSaisi = tfNombre.getText();
        boolean valide = Validation.isIntValid(strSaisi) && Integer.parseInt(strSaisi) > 0;
        btnEnregistrer.setEnabled(valide); lblErreur.setVisible(!valide);
    }//GEN-LAST:event_tfNombreTextValueChanged

    /* L'utilisateur a choisi d'enregistrer la commande */
    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        Commande commande = new Commande(employe, listeCapsules.getCapsuleCourante(), Integer.parseInt(tfNombre.getText()));
        frmMain.enregistreCommande(commande);
        dispose();
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    /* L'utilisateur a changé la sélection de la capsule */
    private void lstCapsulesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstCapsulesItemStateChanged
        selectCapsule(lstCapsules.getSelectedIndex());
    }//GEN-LAST:event_lstCapsulesItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnEnregistrer;
    private java.awt.Label lblEmploye;
    private java.awt.Label lblErreur;
    private java.awt.Label lblNombre;
    private java.awt.List lstCapsules;
    private java.awt.TextField tfNombre;
    // End of variables declaration//GEN-END:variables

} // FrmNouvelleCommande
